---
- name: APT Management
  ansible.builtin.include_role:
    name: common
    tasks_from: apt.yml
  tags: [apt, upgrade]
  vars:
    common_required_packages: "{{ manage_required_packages }}"
    install_docker_repo: "{{ manage_install_docker_repo }}"  # noqa: var-naming[no-role-prefix]
