# SPDX-License-Identifier: MIT-0
---
# defaults file for sub_nginx_3xui
subnginx3xui_required_packages:
  - docker-ce
  - docker-compose-plugin
  - certbot

# Управление установкой Docker репозитория
subnginx3xui_install_docker_repo: true

# Parameters for repository update control
subnginx3xui_update_repo: true
subnginx3xui_force_repo_update: true

# user for folders permission
subnginx3xui_folder_user: "{{ role_name | basename }}"

# Common paths
subnginx3xui_pwd: "/server"
subnginx3xui_nginx_proxy_sub: "{{ subnginx3xui_pwd }}/3x-ui-sub"
subnginx3xui_cert_path: "{{ subnginx3xui_pwd }}/certbot"

# File permissions
subnginx3xui_directory_mode: "0755"
subnginx3xui_file_mode: "0644"
