---
# defaults file for vpn_servers

vpnserver_required_packages:
  - docker-ce
  - docker-compose-plugin
  - curl
  - bash
  - openssl
  - vim
  - sqlite3
  - certbot
  - python3-setuptools
  - fail2ban
  - whois

# Управление установкой Docker репозитория
vpnserver_install_docker_repo: true

# Parameters for repository update control
vpnserver_update_repo: true
vpnserver_force_repo_update: true

# user for folders permission
vpnserver_folder_user: "{{ role_name | basename }}"

# Common paths
vpnserver_pwd: "/server"
vpnserver_path: "{{ vpnserver_pwd }}/vpnserver"
vpnserver_xray_path: "{{ vpnserver_path }}/3x-ui"
vpnserver_xray_db_path: "{{ vpnserver_xray_path }}/db"
vpnserver_cert_path: "{{ vpnserver_pwd }}/certbot"
vpnserver_amneziawg_path: "{{ vpnserver_path }}/amneziawg"
vpnserver_fail2ban_path: "{{ vpnserver_path }}/fail2ban"

# File permissions
vpnserver_directory_mode: "0755"
vpnserver_file_mode: "0600"
