---
watchtower_required_packages:
  - docker-ce
  - docker-compose-plugin

# Управление установкой Docker репозитория
watchtower_install_docker_repo: true

# Parameters for repository update control
watchtower_update_repo: true
watchtower_force_repo_update: false

# user for folders permission
watchtower_folder_user: "{{ role_name | basename }}"

watchtower_pwd: "/server"
watchtower_path: "{{ watchtower_pwd }}/{{ role_name | basename }}"

# File permissions
watchtower_directory_mode: "0755"
watchtower_file_mode: "0644"
