- name: Include common certbot tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: certbot.yml
  vars:
    common_up_handler_name: "docker up vpnserver"
    common_down_handler_name: "docker down vpnserver"
  tags: [ssl]
