---
- name: Import APT management tasks
  ansible.builtin.import_tasks: apt.yml
  tags: [apt, upgrade]

- name: Import certbot tasks
  ansible.builtin.import_tasks: certbot.yml
  tags: [certbot]

- name: Import file copy tasks
  ansible.builtin.import_tasks: filescopy.yml
  tags: [filescopy]

- name: Import 3x-ui tasks
  ansible.builtin.import_tasks: 3x-ui.yml
  tags: [3x-ui]

- name: Import AmneziaWG tasks
  ansible.builtin.import_tasks: amneziawg.yml
  tags: [amneziawg]

- name: Import firewall tasks
  ansible.builtin.import_tasks: firewall.yml
  tags: [firewall]
