- name: Include common certbot tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: certbot.yml
  vars:
    common_up_handler_name: "docker up 3xuiproxy"
    common_down_handler_name: "docker down 3xuiproxy"
    common_domain_name: "{{ sub_all_url }}"
  tags: [ssl]
