---
- name: Include common file copy tasks
  ansible.builtin.import_tasks: ../common/tasks/filescopy.yml
  vars:
    common_up_handler_name: "docker up subnginx3xui"
    common_down_handler_name: "docker down subnginx3xui"
    common_files_source_dir: "{{ lookup('env', 'PWD') }}/roles/subnginx3xui/files/"
    common_folder_user: "{{ subnginx3xui_folder_user }}"
    common_directory_mode: "{{ subnginx3xui_directory_mode }}"
    common_file_mode: "{{ subnginx3xui_file_mode }}"
    common_pwd: "{{ subnginx3xui_pwd }}"
    common_path: "{{ subnginx3xui_path }}"
