---
- name: Include common file copy tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: filescopy.yml
  vars:
    common_common_up_handler_name: "docker up {{ role_name | basename }}"
    common_common_down_handler_name: "docker down {{ role_name | basename }}"
    common_common_files_source_dir: "{{ role_path }}/files/"
    common_folder_user: "{{ subnginx3xui_folder_user }}"
    common_directory_mode: "{{ subnginx3xui_directory_mode }}"
    common_file_mode: "{{ subnginx3xui_file_mode }}"
