---
beszel_required_packages:
  - docker-ce
  - docker-compose-plugin

# Управление установкой Docker репозитория
beszel_install_docker_repo: true

# Parameters for repository update control
beszel_update_repo: true
beszel_force_repo_update: false

# user for folders permission
beszel_folder_user: "{{ role_name | basename }}"

# Common paths
beszel_pwd: "/server"
beszel_path: "{{ beszel_pwd }}/{{ role_name | basename }}"

# File permissions
beszel_directory_mode: "0755"
beszel_file_mode: "0644"
