- name: Include common certbot tasks
  ansible.builtin.include_role:
    name: common
    tasks_from: certbot.yml
  vars:
    common_up_handler_name: "docker up untilwall"
    common_down_handler_name: "docker down untilwall"
    common_domain_name: "{{ untilwall_domain_name }}"
    common_cert_path: "{{ untilwall_cert_path }}"
    common_telegram_notify_enabled: "{{ telegram_notify_enabled | default(false) }}"
    common_telegram_bot_token: "{{ untilwall_telegram_bot_token }}"
    common_telegram_chat_id: "{{ untilwall_telegram_chat_id }}"
    common_telegram_host_name: "{{ inventory_hostname }}"
  tags: [ssl]
