- name: Configure nginx for untilwall
  ansible.builtin.include_role:
    name: common
    tasks_from: nginx.yml
  vars:
    common_nginx_server_name: "{{ untilwall_domain_name }}"
    common_nginx_site_name: "untilwall"
    common_nginx_ssl_enabled: true
    common_nginx_ssl_cert: "{{ untilwall_cert_path }}/live/{{ untilwall_domain_name }}/fullchain.pem"
    common_nginx_ssl_key: "{{ untilwall_cert_path }}/live/{{ untilwall_domain_name }}/privkey.pem"
    common_nginx_backend_port: 3000
  tags: [nginx]
