---
# defaults file for mediaserver
homelab_required_packages:
  - docker-ce
  - docker-compose-plugin

# Управление установкой Docker репозитория
homelab_install_docker_repo: true

# Parameters for repository update control
homelab_update_repo: true
homelab_force_repo_update: false

# user for folders permission
homelab_folder_user: "{{ role_name | basename }}"

# Common paths
homelab_pwd: "/server/"
homelab_path: "{{ homelab_pwd }}/{{ role_name | basename }}"

# File permissions
homelab_directory_mode: "0755"
homelab_file_mode: "0644"

# tautulli
homelab_tautulliport: "8181"
# tailscale proxy
homelab_tsdproxy_enable: true


# transmisiion
homelab_transmission_port: "9091"
homelab_transmission_download_dir: "/mnt/torrent/"
homelab_transmission_incomplete_dir: "/tmp"
homelab_transmission_watch_dir: "/mnt/torrent/new"
# transmisiion-rss
homelab_trans_rss_download_path: "/mnt/torrent"
homelab_trans_rss_url: "https://datalostfilmfeed.byalex.dev/rssfeeds/aa111fef-aa5d-4f43-8a34-191634420162.xml"
homelab_trans_rss_update_interval: "600"
# torrserver
homelab_torrserverport: "8090"
