---
- name: Import APT management tasks
  ansible.builtin.import_tasks: apt.yml
  tags: [apt, upgrade]

- name: Set role-specific media binds
  ansible.builtin.set_fact:
    homelab_role_media_binds: "{{ homelab_media_binds | default([]) }}"

- name: Import file copy tasks
  ansible.builtin.import_tasks: filescopy.yml
  tags: [filescopy]
