# media binds vars
homelab_media_binds:
  - /mnt/torrent:/mnt/torrent
  - /mnt/torrent2:/mnt/torrent2
  - /mnt/torrent3:/mnt/torrent3
  - /mnt/torrent4:/mnt/torrent4
  - /mnt/backup:/mnt/backup


# plex mediaserver vars
plex_claim: "claim-xxx123"
plex_uid: 998
plex_gid: 998
nvidia_gpu_passthrough: true
tsdproxy_enable: true
