---
- name: Docker down {{ role_name | basename }}
  ansible.builtin.command: "{{ common_compose_command | default('docker compose') }} down"
  args:
    chdir: "{{ beszel_path }}"
  register: beszel_compose_down_result
  changed_when: >-
    beszel_compose_down_result.stdout is search('Removing')
    or beszel_compose_down_result.stdout is search('Stopped')
  failed_when: false

- name: Docker up {{ role_name | basename }}
  ansible.builtin.command: "{{ common_compose_command | default('docker compose') }} up -d"
  args:
    chdir: "{{ beszel_path }}"
  register: beszel_compose_up_result
  changed_when: >-
    beszel_compose_up_result.stdout is search('Creating')
    or beszel_compose_up_result.stdout is search('Recreating')
    or beszel_compose_up_result.stdout is search('Starting')
