---
- name: Reboot servers
  hosts: "{{ target_hosts | default('all') }}"
  gather_facts: false
  tasks:
    - name: Send reboot command
      ansible.builtin.command: reboot
      async: 1
      poll: 0
      tags: [reboot]
      failed_when: false
      changed_when: true

    - name: Wait for server to come back
      ansible.builtin.wait_for_connection:
        delay: 30
        timeout: 3600
      tags: [reboot]
