services:
  beszel-agent:
    image: docker.io/henrygd/beszel-agent:0.18.2-alpine
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
    environment:
      LISTEN: "{{manage_beszel_port}}"
      KEY: "{{manage_beszel_public_key}}"
      MEM_CALC: "htop"

  watchtower:
    image: docker.io/nickfedor/watchtower:latest
    container_name: watchtower
    network_mode: host
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCHEDULE=0 */15 * * * *
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_REVIVE_STOPPED=false
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME={{ansible_host}}
      - WATCHTOWER_NOTIFICATIONS=shoutrrr
      - WATCHTOWER_NOTIFICATION_URL=telegram://{{manage_watchtower_tg_wt_bot_token}}@telegram/?channels={{manage_watchtower_tg_wt_chat_id}}
    restart: unless-stopped
